name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
       channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter build web
